export const formDataConstants = {

FETCH_FORM_DATA_PROCESSING:"FETCH_FORM_DATA_PROCESSING",
FETCH_FORM_DATA_ERROR:"FETCH_FORM_DATA_ERROR",
FETCH_FORM_DATA_SUCCESS:"FETCH_FORM_DATA_SUCCESS",

CREATE_FORM_DATA_PROCESSING:"CREATE_FORM_DATA_PROCESSING",
CREATE_FORM_DATA_ERROR:"CREATE_FORM_DATA_ERROR",
CREATE_FORM_DATA_SUCCESS:"CREATE_FORM_DATA_SUCCESS",

DELETE_FORM_DATA_PROCESSING:"DELETE_FORM_DATA_PROCESSING",
DELETE_FORM_DATA_ERROR:"DELETE_FORM_DATA_ERROR",
DELETE_FORM_DATA_SUCCESS:"DELETE_FORM_DATA_SUCCESS"

}